import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "social links profile main",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col w-full md:items-center min-h-screen md:px-60 md:py-24 2xl:px-[780px] 2xl:py-40 bg-neutral-off-black">
          {children}
        </main>
      </body>
    </html>
  );
}
